<?php

$strings = array();

$strings['TITLE_PROJECT_MODULE_NAME'] = 'Project Module Name (lowercase)';
$strings['DESC_PROJECT_MODULE_NAME'] = 'Project specific module name in lowercase (will be cast to lowercase anyway), please make sure the folder "sim" is created in "sites/all/modules/". Max 20 letters.';
$strings['TITLE_PROJECT_CLASS_PREFIX'] = 'Project Class Prefix (UPPERCASE)';
$strings['DESC_PROJECT_CLASS_PREFIX'] = 'Project Class Prefix in UPPERCASE (will be cast to UPPERCASE anyway), will be prepended to every project specific class. Must start with [A-Z] as it must be valid class name, 2-3 letters are recommanded, max 5 letters.';
$strings['TITLE_PROJECT_FIELD_PREFIX_PER_TYPE'] = 'Project Field Prefix (!entity_type : !entity_bundle)';
$strings['TITLE_PROJECT_FIELD_PREFIX'] = 'Project Field Prefix';

$strings['MSG_MODULE_STRUCT_CREATED'] = 'Struct (folders and entity classes) of module !module are created.';